name: Pull Request Workflow
on: [pull_request]
jobs:
  run-tests:
    runs-on: macOS-latest
    timeout-minutes: 15
    steps:
    - name: Git checkout
      uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.ref }}
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Run tests
      run: swift test
      